"""Load challenges from config

Revision ID: e62fd69999999
Revises: 7e9efd084c5b
Create Date: 2017-10-14 14:56:14.215349

"""
import json

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62fd69999999'
down_revision = '7e9efd084c5b'
branch_labels = None
depends_on = None

with open('migrations/challenges', 'r') as file:
        filedata = file.read()
        challenges = json.loads(filedata)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    op.bulk_insert(challenges, challenges)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    # Do not downgrade... just reset your CTFD :)
    # ### end Alembic commands ###
